### ISSUE TITLE
Automatic journal location detection based on platform.

### ISSUE THREAD

**Issue by rster2002** [rster2002/ed-journals#11]
Add a function for detecting where the journal directory is located taking platform into account.

**Comment by Somfic** [comment]
If I’m not mistaken Elite has been discontinued on Mac, and is now only running on Windows, Xbox One and PlayStation 4. Though I am not sure we can run `ed-journals`, or any custom application, on the console platforms (don’t quote me on this), leaving only Windows as a viable platform for the library.

I was wondering what you meant with *“taking platform into account”* if we can only run on Windows? (maybe when using Wine on Linux distros?)

The journals are on Windows are always™️ located in `user profile/Saved Games/Frontier Developments/Elite Dangerous`.

**Comment by rster2002** [comment]
Primarily Linux and Windows. For Windows it's pretty straight forward forward, but for Linux depending on which compatibility layer you're using it can be it different places.

**Comment by rster2002** [comment]
This post on the forum has some of the locations pointed out (for Linux at least) but haven't tested all of them yet. https://forums.frontier.co.uk/threads/solved-linux-journal-files.507750/post-7716832

Probably just has to be a function that has all of these paths listed and just calls `.exists()` in the path returning the first match.
