### ISSUE TITLE
Merging Projects Eventually?

### ISSUE THREAD

**Issue by nixpulvis** [rster2002/ed-journals#90]
Hi, I'm the author of https://github.com/nixpulvis/elite_journal which has the same goals of this project.

I'm working on https://github.com/nixpulvis/galos right now, which has it's own DB, primarily for systems/stars/bodies information, but I'm building it out slowly.

I would be interested in unifying code here, if you are as well.

The one main sticking point I see right now is that I implement `geozero` traits on the system coordinate type so that it can be used in PostGIS without any additional wrapping. Kinda obscure, but it's behind a feature flag.

**Comment by rster2002** [comment]
Hi!

I'm not entirely sure what merging the projects would look like and what the eventual goal would be. I'm not sure if I want to concern ed-journals with specifics like geozero, but maybe that's not the goal. Let me know.

**Comment by nixpulvis** [comment]
I guess the main goal would be to have a single resource for others who want to use this functionality. Since it basically just a collection of structs that need to be kept in sync with elite, this also could help keeping things up to date.

I’m just now slowly starting to work on a Windows application, so I may end up using more of the files than are published through EDDN.

At the end of the day, it’s not a big deal if there’s two similar crates. Just thought I’d see what you thought.

**Comment by rster2002** [comment]
I don't think merging would add any value. If there are differences in how things are handled between the libraries that it wouldn't make sense to merge them as they would fulfill different requirements and if the implementations would largely be the same then merging wouldn't really add anything new.

**Comment by rster2002** [comment]
As a sidenote: if you do have a reason to need code from this project in your own code, and adding this as a dependency is not viable: the project is linenced under an MIT licence so as long as you follow the licence and include the copyright notice you can always just copy the parts you need.

**Comment by nixpulvis** [comment]
Sounds good.
